import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {DEFAULT_PLAYERS, TIMES, absenceReport, dateRange, generateSchedule, normalizeUnavailable, validateSchedule, fairness} from '../src/tennis-core.js';
import {authorizeOAuthRequest, beginOAuth, buildAuthorizationUrl, completeOAuthAuthorization, configuredProviderName, configuredProviders, createLocalOAuthSession, createOAuthChallenge, exchangeAndVerify, exchangeAuthorizationCode, isAdminIdentity, oauthSessionCookie, readOAuthAccessToken, readOAuthSession, registerOAuthClient, requireOAuthProvider, sameSecret} from '../integration/oauth.mjs';
const testPlayers=structuredClone(DEFAULT_PLAYERS);
testPlayers[0].unavailable=['2026-10-31'];
testPlayers[2].unavailable=['2026-11-07','2026-11-14'];
testPlayers[3].unavailable=['2026-11-14','2026-12-05'];
const schedule=generateSchedule(testPlayers);
assert.equal(dateRange().length,30,'all Saturdays in range');
assert.equal(dateRange()[0],'2026-10-03'); assert.equal(dateRange().at(-1),'2027-04-24');
assert.equal(schedule.length,30); assert(schedule.every(d=>d.matches.length===5));
assert.deepEqual(schedule[0].matches.map(m=>m.time),TIMES);
assert(schedule.every(d=>d.matches.flatMap(m=>[m.a,m.b]).filter(Boolean).length===10));
assert.equal(schedule.find(d=>d.date==='2026-10-31').matches.flatMap(m=>[m.a,m.b]).includes('p1'),false);
for(const d of schedule){for(const m of d.matches){assert.notEqual(m.a,m.b);assert(m.a&&m.b);}}
assert.equal(schedule.find(d=>d.date==='2026-11-07').matches.flatMap(m=>[m.a,m.b]).includes('p3'),false);
assert.equal(schedule.find(d=>d.date==='2026-11-07').matches.flatMap(m=>[m.a,m.b]).includes('p4'),true);
assert.equal(schedule.find(d=>d.date==='2026-11-14').matches.flatMap(m=>[m.a,m.b]).includes('p3'),false);
assert.equal(schedule.find(d=>d.date==='2026-11-14').matches.flatMap(m=>[m.a,m.b]).includes('p4'),false);
assert.equal(schedule.find(d=>d.date==='2026-12-05').matches.flatMap(m=>[m.a,m.b]).includes('p4'),false);
assert(schedule.filter(d=>d.date!=='2026-10-31').every(d=>d.matches[0].a==='p1'));
assert(schedule.filter(d=>d.date!=='2026-10-31').every(d=>d.matches[4].b==='p2'));
assert.equal(validateSchedule(schedule,testPlayers).length,0);
const duplicate=structuredClone(schedule);duplicate[0].matches[1].a=duplicate[0].matches[0].a;assert(validateSchedule(duplicate,testPlayers).some(x=>x.includes('doppelt')));
const f=fairness(schedule,testPlayers);assert.equal(Object.keys(f.games).length,12);assert.equal(Object.keys(f.pairs).length,66);assert(Object.values(f.pairs).some(count=>count===0));assert(f.max>=f.min);
const swapped=structuredClone(testPlayers);swapped[0].fixedFirst=false;swapped[2].fixedFirst=true;const swappedPlan=generateSchedule(swapped);assert.equal(validateSchedule(swappedPlan,swapped).length,0);assert(swappedPlan.filter(day=>day.date!=='2026-11-07'&&day.date!=='2026-11-14').every(day=>day.matches[0].a==='p3'));
assert.equal(absenceReport(schedule,testPlayers).length, 4);
assert.deepEqual(normalizeUnavailable('2026-10-31, falsch, 2026-10-31'), {values:['2026-10-31'], invalid:['falsch']});
const html=await readFile(new URL('../index.html',import.meta.url),'utf8');const css=await readFile(new URL('../src/styles.css',import.meta.url),'utf8');
const discovery=JSON.parse(await readFile(new URL('../.well-known/fountain-coach-tennis.json',import.meta.url),'utf8'));const chatgpt=await readFile(new URL('../chatgpt.txt',import.meta.url),'utf8');
assert(html.includes('<html lang="de">')&&html.includes('name="viewport"')&&html.includes('role="status"'));
assert(html.includes('data-tab="schedule"')&&html.includes('data-tab="players"')&&html.includes('data-tab="analysis"'));
assert(html.includes('id="auth-gate"')&&html.includes('href="/auth/login"'),'app must expose an OAuth gate');
assert(html.includes('id="import-local"'),'authenticated app must expose an explicit local-data import action');
const browserSource=await readFile(new URL('../src/tennis.js',import.meta.url),'utf8');assert(browserSource.includes("body: JSON.stringify(request)")&&browserSource.includes("remoteOperation('import_state"),'authenticated browser writes must use the server operation boundary');
assert(css.includes('@media(max-width:800px)')&&css.includes('@media(max-width:480px)'));
assert.equal(discovery.schemaVersion,'fountain-coach.tennis.chatgpt-discovery.v1');assert.equal(discovery.integrationStatus,'read-discovery-ready-mcp-core-ready-public-deployment-not-verified');assert(discovery.mcpEndpoint==='/mcp'&&discovery.mcpTransport==='Streamable HTTP'&&discovery.writeCapabilities.includes('edit_match')&&chatgpt.includes('public HTTPS deployment and ChatGPT connection not verified'));
const oauthEnv={GOOGLE_OAUTH_CLIENT_ID:'google-client',GOOGLE_OAUTH_CLIENT_SECRET:'google-secret',GOOGLE_OAUTH_REDIRECT_URI:'https://tennis.example.test/auth/google/callback',APPLE_OAUTH_CLIENT_ID:'apple-client',APPLE_OAUTH_CLIENT_SECRET:'apple-secret',APPLE_OAUTH_REDIRECT_URI:'https://tennis.example.test/auth/apple/callback',GITHUB_OAUTH_CLIENT_ID:'github-client',GITHUB_OAUTH_CLIENT_SECRET:'github-secret',GITHUB_OAUTH_REDIRECT_URI:'https://tennis.example.test/auth/github/callback'};
assert.deepEqual(Object.keys(configuredProviders(oauthEnv)).sort(),['apple','github','google']);
const challenge=createOAuthChallenge();const googleUrl=new URL(buildAuthorizationUrl('google',challenge,oauthEnv));
assert.equal(googleUrl.searchParams.get('code_challenge_method'),'S256');assert.equal(googleUrl.searchParams.get('state'),challenge.state);assert.equal(googleUrl.searchParams.get('nonce'),challenge.nonce);assert(googleUrl.searchParams.get('code_challenge'));
assert.throws(()=>requireOAuthProvider('google',{}),/not configured/);assert(sameSecret('token','token')&&!sameSecret('token','other'));assert(oauthSessionCookie('session-token',{production:true}).includes('HttpOnly')&&oauthSessionCookie('session-token',{production:true}).includes('Secure'));
assert.equal(configuredProviderName({...oauthEnv,OAUTH_IDP:'github'}),'github');
const login=beginOAuth('google',oauthEnv);assert(login.authorizationUrl.includes('accounts.google.com'));assert(login.state);
const githubChallenge=createOAuthChallenge();const githubUrl=new URL(buildAuthorizationUrl('github',githubChallenge,oauthEnv));
assert.equal(githubUrl.origin,'https://github.com');assert.equal(githubUrl.pathname,'/login/oauth/authorize');assert.equal(githubUrl.searchParams.get('code_challenge_method'),'S256');assert(githubUrl.searchParams.get('scope').includes('user:email'));
const githubFetch=async (url, options={}) => {
  if (url === 'https://github.com/login/oauth/access_token') return {ok:true,json:async()=>({access_token:'github-access-token'})};
  if (url === 'https://api.github.com/user') return {ok:true,json:async()=>({id:12345})};
  if (url === 'https://api.github.com/user/emails') return {ok:true,json:async()=>[{email:'Admin@Example.Test',primary:true,verified:true}]};
  throw new Error(`unexpected GitHub URL: ${url}`);
};
const githubIdentity=await exchangeAndVerify('github',{code:'github-code',codeVerifier:githubChallenge.codeVerifier,state:githubChallenge.state,expectedState:githubChallenge.state,nonce:githubChallenge.nonce},oauthEnv,githubFetch);
assert.deepEqual(githubIdentity,{provider:'github',subject:'12345',email:'admin@example.test'});
const client=registerOAuthClient({redirectUris:['https://chat.openai.com/aip/oauth/callback'],clientName:'ChatGPT'});assert.equal(client.token_endpoint_auth_method,'none');
const authChallenge=createOAuthChallenge();const authRequest=authorizeOAuthRequest({clientId:client.client_id,redirectUri:client.redirect_uris[0],state:'chat-state',codeChallenge:authChallenge.codeChallenge,codeChallengeMethod:'S256',scope:'openid offline_access tennis.read tennis.write'},{...oauthEnv,OAUTH_IDP:'google'});assert(authRequest.authorizationUrl.includes('accounts.google.com'));
const adminEnv={...oauthEnv,TENNIS_ADMIN_EMAILS:'admin@example.test'};assert(isAdminIdentity({email:'admin@example.test'},adminEnv)&&!isAdminIdentity({email:'member@example.test'},adminEnv));
const localSession=createLocalOAuthSession({email:'local-admin@example.test'});assert.equal(readOAuthSession(localSession)?.provider,'local');assert.equal(readOAuthSession(localSession)?.email,'local-admin@example.test');
const code=completeOAuthAuthorization({provider:'google',subject:'admin-subject',email:'admin@example.test'},{clientId:client.client_id,redirectUri:client.redirect_uris[0],state:'chat-state',codeChallenge:authChallenge.codeChallenge,scope:'openid offline_access tennis.read tennis.write'},adminEnv);const tokens=exchangeAuthorizationCode({code,clientId:client.client_id,redirectUri:client.redirect_uris[0],codeVerifier:authChallenge.codeVerifier});assert(tokens.access_token&&tokens.refresh_token&&readOAuthAccessToken(tokens.access_token)?.email==='admin@example.test');
await assert.rejects(()=>exchangeAndVerify('google',{code:'code',codeVerifier:'verifier',state:'wrong',expectedState:'expected',nonce:'nonce'},oauthEnv,()=>{throw new Error('network must not be reached');}),/callback rejected/);
console.log('PASS 25 tennis acceptance assertions');
